# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mb5018/Desktop/fpga-piano-master/fpga_piano_proj/fpga_piano_proj.cache/wt [current_project]
set_property parent.project_path C:/Users/mb5018/Desktop/fpga-piano-master/fpga_piano_proj/fpga_piano_proj.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/mb5018/Desktop/fpga-piano-master/fpga_piano_proj/fpga_piano_proj.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/mb5018/Desktop/fpga-piano-master/piano_lab/src/clk_dvd.vhd
  C:/Users/mb5018/Desktop/fpga-piano-master/piano_lab/src/note_gen.vhd
  C:/Users/mb5018/Desktop/fpga-piano-master/piano_lab/src/seven_seg.vhd
  C:/Users/mb5018/Desktop/fpga-piano-master/piano_lab/src/piano.vhd
}
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/mb5018/Desktop/fpga-piano-master/piano_lab/src/Basys3_Master.xdc
set_property used_in_implementation false [get_files C:/Users/mb5018/Desktop/fpga-piano-master/piano_lab/src/Basys3_Master.xdc]


synth_design -top piano -part xc7a35tcpg236-1


write_checkpoint -force -noxdef piano.dcp

catch { report_utilization -file piano_utilization_synth.rpt -pb piano_utilization_synth.pb }
